package com.com.poke.rng.dsum.constants;

import java.lang.reflect.Executable;
import java.util.Collections;
import java.util.EnumMap;
import java.util.Map;

import static com.com.poke.rng.dsum.constants.Encounter.of;
import static com.com.poke.rng.dsum.constants.Species.*;

public enum Route {
    ROUTE_1(
            of(Pidgey, 3),
            of(Rattata, 3),
            of(Rattata, 3),
            of(Rattata, 2),
            of(Pidgey, 2),
            of(Pidgey, 3),
            of(Pidgey, 3),
            of(Rattata, 4),
            of(Pidgey, 4),
            of(Pidgey, 5)
    ),
    ROUTE_2(
            of(Rattata, 3),
            of(Pidgey, 3),
            of(Pidgey, 4),
            of(Rattata, 4),
            of(Pidgey, 5),
            of(Caterpie, 3),
            of(Rattata, 2),
            of(Rattata, 5),
            of(Caterpie, 4),
            of(Caterpie, 5),

            of(Rattata, 3),
            of(Pidgey, 3),
            of(Pidgey, 4),
            of(Rattata, 4),
            of(Pidgey, 5),
            of(Weedle, 3),
            of(Rattata, 2),
            of(Rattata, 5),
            of(Weedle, 4),
            of(Weedle, 5)
    ),
    ROUTE_3(
            of(Pidgey, 6),
            of(Spearow, 5),
            of(Pidgey, 7),
            of(Spearow, 6),
            of(Spearow, 7),
            of(Pidgey, 8),
            of(Spearow, 8),
            of(Jigglypuff, 3),
            of(Jigglypuff, 5),
            of(Jigglypuff, 7)
    ),
    ROUTE_4(
            of(Rattata, 10),
            of(Spearow, 10),
            of(Rattata, 8),
            of(Sandshrew, 6),
            of(Spearow, 8),
            of(Sandshrew, 10),
            of(Rattata, 12),
            of(Spearow, 12),
            of(Sandshrew, 8),
            of(Sandshrew, 12),

            of(Rattata, 10),
            of(Spearow, 10),
            of(Rattata, 8),
            of(Ekans, 6),
            of(Spearow, 8),
            of(Ekans, 10),
            of(Rattata, 12),
            of(Spearow, 12),
            of(Ekans, 8),
            of(Ekans, 12)
    ),
    ROUTE_5(
            of(Bellsprout, 13),
            of(Pidgey, 13),
            of(Pidgey, 15),
            of(Meowth, 10),
            of(Meowth, 12),
            of(Bellsprout, 15),
            of(Bellsprout, 16),
            of(Pidgey, 16),
            of(Meowth, 14),
            of(Meowth, 16),

            of(Oddish, 13),
            of(Pidgey, 13),
            of(Pidgey, 15),
            of(Mankey, 10),
            of(Mankey, 12),
            of(Oddish, 15),
            of(Oddish, 16),
            of(Pidgey, 16),
            of(Mankey, 14),
            of(Mankey, 16)
    ),
    ROUTE_6(
            of(Bellsprout, 13),
            of(Pidgey, 13),
            of(Pidgey, 15),
            of(Meowth, 10),
            of(Meowth, 12),
            of(Bellsprout, 15),
            of(Bellsprout, 16),
            of(Pidgey, 16),
            of(Meowth, 14),
            of(Meowth, 16),

            of(Oddish, 13),
            of(Pidgey, 13),
            of(Pidgey, 15),
            of(Mankey, 10),
            of(Mankey, 12),
            of(Oddish, 15),
            of(Oddish, 16),
            of(Pidgey, 16),
            of(Mankey, 14),
            of(Mankey, 16)
    ),
    ROUTE_7(
            of(Pidgey, 19),
            of(Bellsprout, 19),
            of(Meowth, 17),
            of(Bellsprout, 22),
            of(Pidgey, 22),
            of(Meowth, 18),
            of(Vulpix, 18),
            of(Vulpix, 20),
            of(Meowth, 19),
            of(Meowth, 20),

            of(Pidgey, 19),
            of(Oddish, 19),
            of(Mankey, 17),
            of(Oddish, 22),
            of(Pidgey, 22),
            of(Mankey, 18),
            of(Growlithe, 18),
            of(Growlithe, 20),
            of(Mankey, 19),
            of(Mankey, 20)
    ),
    ROUTE_8(
            of(Pidgey, 18),
            of(Meowth, 18),
            of(Sandshrew, 17),
            of(Vulpix, 16),
            of(Pidgey, 20),
            of(Meowth, 20),
            of(Sandshrew, 19),
            of(Vulpix, 17),
            of(Vulpix, 15),
            of(Vulpix, 18),

            of(Pidgey, 18),
            of(Mankey, 18),
            of(Ekans, 17),
            of(Growlithe, 16),
            of(Pidgey, 20),
            of(Mankey, 20),
            of(Ekans, 19),
            of(Growlithe, 17),
            of(Growlithe, 15),
            of(Growlithe, 18)
    ),
    ROUTE_9(
            of(Rattata, 16),
            of(Spearow, 16),
            of(Rattata, 14),
            of(Sandshrew, 11),
            of(Spearow, 13),
            of(Sandshrew, 15),
            of(Rattata, 17),
            of(Spearow, 17),
            of(Sandshrew, 13),
            of(Sandshrew, 17),

            of(Rattata, 16),
            of(Spearow, 16),
            of(Rattata, 14),
            of(Ekans, 11),
            of(Spearow, 13),
            of(Ekans, 15),
            of(Rattata, 17),
            of(Spearow, 17),
            of(Ekans, 13),
            of(Ekans, 17)
    ),
    ROUTE_10(
            of(Voltorb, 16),
            of(Spearow, 16),
            of(Voltorb, 14),
            of(Sandshrew, 11),
            of(Spearow, 13),
            of(Sandshrew, 15),
            of(Voltorb, 17),
            of(Spearow, 17),
            of(Sandshrew, 13),
            of(Sandshrew, 17),

            of(Voltorb, 16),
            of(Spearow, 16),
            of(Voltorb, 14),
            of(Ekans, 11),
            of(Spearow, 13),
            of(Ekans, 15),
            of(Voltorb, 17),
            of(Spearow, 17),
            of(Ekans, 13),
            of(Ekans, 17)
    ),
    ROUTE_11(
            of(Sandshrew, 14),
            of(Spearow, 15),
            of(Sandshrew, 12),
            of(Drowzee, 9),
            of(Spearow, 13),
            of(Drowzee, 13),
            of(Sandshrew, 15),
            of(Spearow, 17),
            of(Drowzee, 11),
            of(Drowzee, 15),

            of(Ekans, 14),
            of(Spearow, 15),
            of(Ekans, 12),
            of(Drowzee, 9),
            of(Spearow, 13),
            of(Drowzee, 13),
            of(Ekans, 15),
            of(Spearow, 17),
            of(Drowzee, 11),
            of(Drowzee, 15)
    ),
    ROUTE_12(
            of(Bellsprout, 24),
            of(Pidgey, 25),
            of(Pidgey, 23),
            of(Venonat, 24),
            of(Bellsprout, 22),
            of(Venonat, 26),
            of(Bellsprout, 26),
            of(Pidgey, 27),
            of(Weepinbell, 28),
            of(Weepinbell, 30),

            of(Oddish, 24),
            of(Pidgey, 25),
            of(Pidgey, 23),
            of(Venonat, 24),
            of(Oddish, 22),
            of(Venonat, 26),
            of(Oddish, 26),
            of(Pidgey, 27),
            of(Gloom, 28),
            of(Gloom, 30)
    ),
    ROUTE_13(
            of(Bellsprout, 24),
            of(Pidgey, 25),
            of(Pidgey, 27),
            of(Venonat, 24),
            of(Bellsprout, 22),
            of(Venonat, 26),
            of(Bellsprout, 26),
            of(Ditto, 25),
            of(Weepinbell, 28),
            of(Weepinbell, 30),

            of(Oddish, 24),
            of(Pidgey, 25),
            of(Pidgey, 27),
            of(Venonat, 24),
            of(Oddish, 22),
            of(Venonat, 26),
            of(Oddish, 26),
            of(Ditto, 25),
            of(Gloom, 28),
            of(Gloom, 30)
    ),
    ROUTE_14(
            of(Bellsprout, 24),
            of(Pidgey, 26),
            of(Ditto, 23),
            of(Venonat, 24),
            of(Bellsprout, 22),
            of(Venonat, 26),
            of(Bellsprout, 26),
            of(Weepinbell, 30),
            of(Pidgeotto, 28),
            of(Pidgeotto, 30),

            of(Oddish, 24),
            of(Pidgey, 26),
            of(Ditto, 23),
            of(Venonat, 24),
            of(Oddish, 22),
            of(Venonat, 26),
            of(Oddish, 26),
            of(Gloom, 30),
            of(Pidgeotto, 28),
            of(Pidgeotto, 30)
    ),
    ROUTE_15(
            of(Bellsprout, 24),
            of(Ditto, 26),
            of(Pidgey, 23),
            of(Venonat, 26),
            of(Bellsprout, 22),
            of(Venonat, 28),
            of(Bellsprout, 26),
            of(Weepinbell, 30),
            of(Pidgeotto, 28),
            of(Pidgeotto, 30),

            of(Oddish, 24),
            of(Ditto, 26),
            of(Pidgey, 23),
            of(Venonat, 26),
            of(Oddish, 22),
            of(Venonat, 28),
            of(Oddish, 26),
            of(Gloom, 30),
            of(Pidgeotto, 28),
            of(Pidgeotto, 30)
    ),
    ROUTE_16(
            of(Spearow, 20),
            of(Spearow, 22),
            of(Rattata, 18),
            of(Doduo, 20),
            of(Rattata, 20),
            of(Doduo, 18),
            of(Doduo, 22),
            of(Rattata, 22),
            of(Raticate, 23),
            of(Raticate, 25)
    ),
    ROUTE_17(
            of(Spearow, 20),
            of(Spearow, 22),
            of(Raticate, 25),
            of(Doduo, 24),
            of(Raticate, 27),
            of(Doduo, 26),
            of(Doduo, 28),
            of(Raticate, 29),
            of(Fearow, 25),
            of(Fearow, 27)
    ),
    ROUTE_18(
            of(Spearow, 20),
            of(Spearow, 22),
            of(Raticate, 25),
            of(Doduo, 24),
            of(Fearow, 25),
            of(Doduo, 26),
            of(Doduo, 28),
            of(Raticate, 29),
            of(Fearow, 27),
            of(Fearow, 29)
    ),
    //    ROUTE_19(
    //            of(Tentacool, 5),
    //            of(Tentacool, 10),
    //            of(Tentacool, 15),
    //            of(Tentacool, 5),
    //            of(Tentacool, 10),
    //            of(Tentacool, 15),
    //            of(Tentacool, 20),
    //            of(Tentacool, 30),
    //            of(Tentacool, 35),
    //            of(Tentacool, 40)
    //    ),
    //    ROUTE_20(
    //            of(Tentacool, 5),
    //            of(Tentacool, 10),
    //            of(Tentacool, 15),
    //            of(Tentacool, 5),
    //            of(Tentacool, 10),
    //            of(Tentacool, 15),
    //            of(Tentacool, 20),
    //            of(Tentacool, 30),
    //            of(Tentacool, 35),
    //            of(Tentacool, 40)
    //    ),
    ROUTE_21(
            of(Rattata, 21),
            of(Pidgey, 23),
            of(Raticate, 30),
            of(Rattata, 23),
            of(Pidgey, 21),
            of(Pidgeotto, 30),
            of(Pidgeotto, 32),
            of(Tangela, 28),
            of(Tangela, 30),
            of(Tangela, 32)
    ),
    ROUTE_22(
            of(Rattata, 3),
            of(NidoranF, 3),
            of(Rattata, 4),
            of(NidoranF, 4),
            of(Rattata, 2),
            of(NidoranF, 2),
            of(Spearow, 3),
            of(Spearow, 5),
            of(NidoranM, 3),
            of(NidoranM, 4),

            of(Rattata, 3),
            of(NidoranM, 3),
            of(Rattata, 4),
            of(NidoranM, 4),
            of(Rattata, 2),
            of(NidoranM, 2),
            of(Spearow, 3),
            of(Spearow, 5),
            of(NidoranF, 3),
            of(NidoranF, 4)
    ),
    ROUTE_23(
            of(Ekans, 26),
            of(Ditto, 33),
            of(Spearow, 26),
            of(Fearow, 38),
            of(Ditto, 38),
            of(Fearow, 38),
            of(Sandslash, 41),
            of(Ditto, 43),
            of(Fearow, 41),
            of(Fearow, 43),

            of(Ekans, 26),
            of(Ditto, 33),
            of(Spearow, 26),
            of(Fearow, 38),
            of(Ditto, 38),
            of(Fearow, 38),
            of(Arbok, 41),
            of(Ditto, 43),
            of(Fearow, 41),
            of(Fearow, 43)
    ),
    ROUTE_24(
            of(Caterpie, 7),
            of(Metapod, 8),
            of(Pidgey, 12),
            of(Bellsprout, 12),
            of(Bellsprout, 13),
            of(Abra, 10),
            of(Bellsprout, 14),
            of(Pidgey, 13),
            of(Abra, 8),
            of(Abra, 12),

            of(Weedle, 7),
            of(Kakuna, 8),
            of(Pidgey, 12),
            of(Oddish, 12),
            of(Oddish, 13),
            of(Abra, 10),
            of(Oddish, 14),
            of(Pidgey, 13),
            of(Abra, 8),
            of(Abra, 12)
    ),
    ROUTE_25(
            of(Caterpie, 8),
            of(Metapod, 9),
            of(Pidgey, 13),
            of(Bellsprout, 12),
            of(Bellsprout, 13),
            of(Abra, 12),
            of(Bellsprout, 14),
            of(Abra, 10),
            of(Kakuna, 7),
            of(Weedle, 8),

            of(Weedle, 8),
            of(Kakuna, 9),
            of(Pidgey, 13),
            of(Oddish, 12),
            of(Oddish, 13),
            of(Abra, 12),
            of(Oddish, 14),
            of(Abra, 10),
            of(Metapod, 7),
            of(Caterpie, 8)
    ),
    VIRIDIAN_FOREST(true,
            of(Caterpie, 4),
            of(Metapod, 5),
            of(Caterpie, 3),
            of(Caterpie, 5),
            of(Metapod, 4),
            of(Metapod, 6),
            of(Kakuna, 4),
            of(Weedle, 3),
            of(Pikachu, 3),
            of(Pikachu, 5),

            of(Weedle, 4),
            of(Kakuna, 5),
            of(Weedle, 3),
            of(Weedle, 5),
            of(Kakuna, 4),
            of(Kakuna, 6),
            of(Metapod, 4),
            of(Caterpie, 3),
            of(Pikachu, 3),
            of(Pikachu, 5)
    ),
    MT_MOON_1F(true,
            of(Zubat, 8),
            of(Zubat, 7),
            of(Zubat, 9),
            of(Geodude, 8),
            of(Zubat, 6),
            of(Zubat, 10),
            of(Geodude, 10),
            of(Paras, 8),
            of(Zubat, 11),
            of(Clefairy, 8)
    ),
    MT_MOON_B1F(true,
            of(Zubat, 8),
            of(Zubat, 7),
            of(Geodude, 7),
            of(Geodude, 8),
            of(Zubat, 9),
            of(Paras, 10),
            of(Zubat, 10),
            of(Zubat, 11),
            of(Clefairy, 9),
            of(Geodude, 9)
    ),
    MT_MOON_B2F(true,
            of(Zubat, 9),
            of(Geodude, 9),
            of(Zubat, 10),
            of(Geodude, 10),
            of(Zubat, 11),
            of(Paras, 10),
            of(Paras, 12),
            of(Clefairy, 10),
            of(Zubat, 12),
            of(Clefairy, 12)
    ),
    DIGLETTS_CAVE(
            of(Diglett, 18),
            of(Diglett, 19),
            of(Diglett, 17),
            of(Diglett, 20),
            of(Diglett, 16),
            of(Diglett, 15),
            of(Diglett, 21),
            of(Diglett, 22),
            of(Dugtrio, 29),
            of(Dugtrio, 31)
    ),
    ROCK_TUNNEL_1F(true,
            of(Zubat, 16),
            of(Zubat, 17),
            of(Geodude, 17),
            of(Machop, 15),
            of(Geodude, 16),
            of(Zubat, 18),
            of(Zubat, 15),
            of(Machop, 17),
            of(Onix, 13),
            of(Onix, 15)
    ),
    ROCK_TUNNEL_B1F(true,
            of(Zubat, 16),
            of(Zubat, 17),
            of(Geodude, 17),
            of(Machop, 15),
            of(Geodude, 16),
            of(Zubat, 18),
            of(Machop, 17),
            of(Onix, 17),
            of(Onix, 13),
            of(Geodude, 18)
    ),
    POKEMON_TOWER_3F(true,
            of(Gastly, 20),
            of(Gastly, 21),
            of(Gastly, 22),
            of(Gastly, 23),
            of(Gastly, 19),
            of(Gastly, 18),
            of(Gastly, 24),
            of(Cubone, 20),
            of(Cubone, 22),
            of(Haunter, 25)
    ),
    POKEMON_TOWER_4F(true,
            of(Gastly, 20),
            of(Gastly, 21),
            of(Gastly, 22),
            of(Gastly, 23),
            of(Gastly, 19),
            of(Gastly, 18),
            of(Haunter, 25),
            of(Cubone, 20),
            of(Cubone, 22),
            of(Gastly, 24)
    ),
    POKEMON_TOWER_5F(true,
            of(Gastly, 20),
            of(Gastly, 21),
            of(Gastly, 22),
            of(Gastly, 23),
            of(Gastly, 19),
            of(Gastly, 18),
            of(Haunter, 25),
            of(Cubone, 20),
            of(Cubone, 22),
            of(Gastly, 24)
    ),
    POKEMON_TOWER_6F(true,
            of(Gastly, 21),
            of(Gastly, 22),
            of(Gastly, 23),
            of(Gastly, 24),
            of(Gastly, 20),
            of(Gastly, 19),
            of(Haunter, 26),
            of(Cubone, 22),
            of(Cubone, 24),
            of(Haunter, 28)
    ),
    POKEMON_TOWER_7F(true,
            of(Gastly, 21),
            of(Gastly, 22),
            of(Gastly, 23),
            of(Gastly, 24),
            of(Gastly, 20),
            of(Haunter, 28),
            of(Cubone, 22),
            of(Cubone, 24),
            of(Haunter, 28),
            of(Haunter, 30)
    ),
    SAFARI_ZONE_CENTER(true,
            of(NidoranF, 22),
            of(Rhyhorn, 25),
            of(Venonat, 22),
            of(Exeggcute, 24),
            of(Nidorina, 31),
            of(Exeggcute, 25),
            of(Nidorino, 31),
            of(Parasect, 30),
            of(Pinsir, 23),
            of(Chansey, 23),

            of(NidoranM, 22),
            of(Rhyhorn, 25),
            of(Venonat, 22),
            of(Exeggcute, 24),
            of(Nidorino, 31),
            of(Exeggcute, 25),
            of(Nidorina, 31),
            of(Parasect, 30),
            of(Scyther, 23),
            of(Chansey, 23)
    ),
    SAFARI_ZONE_EAST(true,
            of(NidoranF, 24),
            of(Doduo, 26),
            of(Paras, 22),
            of(Exeggcute, 25),
            of(Nidorina, 33),
            of(Exeggcute, 23),
            of(NidoranM, 24),
            of(Parasect, 25),
            of(Kangaskhan, 25),
            of(Pinsir, 28),

            of(NidoranM, 24),
            of(Doduo, 26),
            of(Paras, 22),
            of(Exeggcute, 25),
            of(Nidorino, 33),
            of(Exeggcute, 23),
            of(NidoranF, 24),
            of(Parasect, 25),
            of(Kangaskhan, 25),
            of(Scyther, 28)
    ),
    SAFARI_ZONE_2(true,
            of(NidoranF, 22),
            of(Rhyhorn, 26),
            of(Paras, 23),
            of(Exeggcute, 25),
            of(Nidorina, 30),
            of(Exeggcute, 27),
            of(Nidorino, 30),
            of(Venomoth, 32),
            of(Chansey, 26),
            of(Tauros, 28),

            of(NidoranM, 22),
            of(Rhyhorn, 26),
            of(Paras, 23),
            of(Exeggcute, 25),
            of(Nidorino, 30),
            of(Exeggcute, 27),
            of(Nidorina, 30),
            of(Venomoth, 32),
            of(Chansey, 26),
            of(Tauros, 28)
    ),
    SAFARI_ZONE_3(true,
            of(NidoranF, 25),
            of(Doduo, 26),
            of(Venonat, 23),
            of(Exeggcute, 24),
            of(Nidorina, 33),
            of(Exeggcute, 26),
            of(NidoranM, 25),
            of(Venomoth, 31),
            of(Tauros, 26),
            of(Kangaskhan, 28),

            of(NidoranM, 25),
            of(Doduo, 26),
            of(Venonat, 23),
            of(Exeggcute, 24),
            of(Nidorino, 33),
            of(Exeggcute, 26),
            of(NidoranF, 25),
            of(Venomoth, 31),
            of(Tauros, 26),
            of(Kangaskhan, 28)
    ),
    POWER_PLANT(
            of(Voltorb, 21),
            of(Magnemite, 21),
            of(Pikachu, 20),
            of(Pikachu, 24),
            of(Magnemite, 23),
            of(Voltorb, 23),
            of(Magneton, 32),
            of(Magneton, 35),
            of(Raichu, 33),
            of(Raichu, 36),

            of(Voltorb, 21),
            of(Magnemite, 21),
            of(Pikachu, 20),
            of(Pikachu, 24),
            of(Magnemite, 23),
            of(Voltorb, 23),
            of(Magneton, 32),
            of(Magneton, 35),
            of(Electabuzz, 33),
            of(Electabuzz, 36)
    ),
    SEAFOAM_ISLANDS_1F(true,
            of(Seel, 30),
            of(Psyduck, 30),
            of(Staryu, 30),
            of(Krabby, 30),
            of(Krabby, 28),
            of(Zubat, 21),
            of(Golbat, 29),
            of(Slowpoke, 28),
            of(Staryu, 28),
            of(Slowbro, 38),

            of(Seel, 30),
            of(Slowpoke, 30),
            of(Shellder, 30),
            of(Horsea, 30),
            of(Horsea, 28),
            of(Zubat, 21),
            of(Golbat, 29),
            of(Psyduck, 28),
            of(Shellder, 28),
            of(Golduck, 38)
    ),
    SEAFOAM_ISLANDS_B1F(true,
            of(Shellder, 30),
            of(Krabby, 30),
            of(Staryu, 32),
            of(Krabby, 32),
            of(Psyduck, 28),
            of(Seel, 30),
            of(Psyduck, 30),
            of(Seel, 28),
            of(Dewgong, 38),
            of(Kingler, 37),

            of(Staryu, 30),
            of(Horsea, 30),
            of(Shellder, 32),
            of(Horsea, 32),
            of(Slowpoke, 28),
            of(Seel, 30),
            of(Slowpoke, 30),
            of(Seel, 28),
            of(Dewgong, 38),
            of(Seadra, 37)
    ),
    SEAFOAM_ISLANDS_B2F(true,
            of(Seel, 30),
            of(Psyduck, 30),
            of(Seel, 32),
            of(Psyduck, 32),
            of(Krabby, 28),
            of(Shellder, 30),
            of(Krabby, 30),
            of(Staryu, 28),
            of(Golbat, 30),
            of(Golduck, 37),

            of(Seel, 30),
            of(Slowpoke, 30),
            of(Seel, 32),
            of(Slowpoke, 32),
            of(Horsea, 28),
            of(Staryu, 30),
            of(Horsea, 30),
            of(Shellder, 28),
            of(Golbat, 30),
            of(Slowbro, 37)
    ),
    SEAFOAM_ISLANDS_B3F(true,
            of(Psyduck, 31),
            of(Seel, 31),
            of(Psyduck, 33),
            of(Seel, 33),
            of(Krabby, 29),
            of(Staryu, 31),
            of(Krabby, 31),
            of(Staryu, 29),
            of(Kingler, 39),
            of(Dewgong, 37),

            of(Slowpoke, 31),
            of(Seel, 31),
            of(Slowpoke, 33),
            of(Seel, 33),
            of(Horsea, 29),
            of(Shellder, 31),
            of(Horsea, 31),
            of(Shellder, 29),
            of(Seadra, 39),
            of(Dewgong, 37)
    ),
    SEAFOAM_ISLANDS_B4F(true,
            of(Krabby, 31),
            of(Staryu, 31),
            of(Krabby, 33),
            of(Staryu, 33),
            of(Psyduck, 29),
            of(Seel, 31),
            of(Psyduck, 31),
            of(Seel, 29),
            of(Golduck, 39),
            of(Golbat, 32),

            of(Horsea, 31),
            of(Shellder, 31),
            of(Horsea, 33),
            of(Shellder, 33),
            of(Slowpoke, 29),
            of(Seel, 31),
            of(Slowpoke, 31),
            of(Seel, 29),
            of(Slowbro, 39),
            of(Golbat, 32)
    ),
    POKEMON_MANSION_1F(
            of(Grimer, 32),
            of(Grimer, 30),
            of(Ponyta, 34),
            of(Ponyta, 30),
            of(Vulpix, 34),
            of(Ponyta, 32),
            of(Koffing, 30),
            of(Ponyta, 28),
            of(Muk, 37),
            of(Weezing, 39),

            of(Koffing, 32),
            of(Koffing, 30),
            of(Ponyta, 34),
            of(Ponyta, 30),
            of(Growlithe, 34),
            of(Ponyta, 32),
            of(Grimer, 30),
            of(Ponyta, 28),
            of(Weezing, 37),
            of(Muk, 39)
    ),
    POKEMON_MANSION_2F(
            of(Vulpix, 32),
            of(Grimer, 34),
            of(Grimer, 34),
            of(Ponyta, 30),
            of(Grimer, 30),
            of(Ponyta, 32),
            of(Koffing, 30),
            of(Ponyta, 28),
            of(Muk, 39),
            of(Weezing, 37),

            of(Growlithe, 32),
            of(Koffing, 34),
            of(Koffing, 34),
            of(Ponyta, 30),
            of(Koffing, 30),
            of(Ponyta, 32),
            of(Grimer, 30),
            of(Ponyta, 28),
            of(Weezing, 39),
            of(Muk, 37)
    ),
    POKEMON_MANSION_3F(
            of(Grimer, 31),
            of(Vulpix, 33),
            of(Grimer, 35),
            of(Ponyta, 32),
            of(Magmar, 34),
            of(Muk, 40),
            of(Koffing, 34),
            of(Muk, 38),
            of(Ponyta, 36),
            of(Weezing, 42),

            of(Koffing, 31),
            of(Growlithe, 33),
            of(Koffing, 35),
            of(Ponyta, 32),
            of(Ponyta, 34),
            of(Weezing, 40),
            of(Grimer, 34),
            of(Weezing, 38),
            of(Ponyta, 36),
            of(Muk, 42)
    ),
    POKEMON_MANSION_B1F(
            of(Grimer, 33),
            of(Grimer, 31),
            of(Vulpix, 35),
            of(Ponyta, 32),
            of(Grimer, 31),
            of(Muk, 40),
            of(Ponyta, 34),
            of(Koffing, 35),
            of(Magmar, 38),
            of(Weezing, 42),

            of(Koffing, 33),
            of(Koffing, 31),
            of(Growlithe, 35),
            of(Ponyta, 32),
            of(Koffing, 31),
            of(Weezing, 40),
            of(Ponyta, 34),
            of(Grimer, 35),
            of(Weezing, 38),
            of(Muk, 42)
    ),
    VICTORY_ROAD_1F(
            of(Machop, 24),
            of(Geodude, 26),
            of(Zubat, 22),
            of(Onix, 36),
            of(Onix, 39),
            of(Onix, 42),
            of(Graveler, 41),
            of(Golbat, 41),
            of(Machoke, 42),
            of(Marowak, 43)
    ),
    VICTORY_ROAD_2F(
            of(Machop, 22),
            of(Geodude, 24),
            of(Zubat, 26),
            of(Onix, 36),
            of(Onix, 39),
            of(Onix, 42),
            of(Machoke, 41),
            of(Golbat, 40),
            of(Marowak, 40),
            of(Graveler, 43)
    ),
    VICTORY_ROAD_3F(
            of(Machop, 24),
            of(Geodude, 26),
            of(Zubat, 22),
            of(Onix, 42),
            of(Venomoth, 40),
            of(Onix, 45),
            of(Graveler, 43),
            of(Golbat, 41),
            of(Machoke, 42),
            of(Machoke, 45)
    ),
    CERULEAN_CAVE_1F(true,
            of(Golbat, 46),
            of(Hypno, 46),
            of(Magneton, 46),
            of(Dodrio, 49),
            of(Venomoth, 49),
            of(Sandslash, 52),
            of(Kadabra, 49),
            of(Parasect, 52),
            of(Raichu, 53),
            of(Ditto, 53),

            of(Golbat, 46),
            of(Hypno, 46),
            of(Magneton, 46),
            of(Dodrio, 49),
            of(Venomoth, 49),
            of(Arbok, 52),
            of(Kadabra, 49),
            of(Parasect, 52),
            of(Raichu, 53),
            of(Ditto, 53)
    ),
    CERULEAN_CAVE_2F(true,
            of(Dodrio, 51),
            of(Venomoth, 51),
            of(Kadabra, 51),
            of(Rhydon, 52),
            of(Marowak, 52),
            of(Electrode, 52),
            of(Chansey, 56),
            of(Wigglytuff, 54),
            of(Ditto, 55),
            of(Ditto, 60)
    ),
    CERULEAN_CAVE_B1F(true,
            of(Rhydon, 55),
            of(Marowak, 55),
            of(Electrode, 55),
            of(Chansey, 64),
            of(Parasect, 64),
            of(Raichu, 64),
            of(Sandslash, 57),
            of(Ditto, 65),
            of(Ditto, 63),
            of(Ditto, 67),

            of(Rhydon, 55),
            of(Marowak, 55),
            of(Electrode, 55),
            of(Chansey, 64),
            of(Parasect, 64),
            of(Raichu, 64),
            of(Arbok, 57),
            of(Ditto, 65),
            of(Ditto, 63),
            of(Ditto, 67)
    );

    private final Map<Game, Map<EncounterSlot, Encounter>> encounters;
    private final boolean isBlinds;

    Route(final Encounter... encounters) {
        this(false, encounters);
    }

    Route(final boolean isBlinds, final Encounter... encounters) {
        this.isBlinds = isBlinds;
        this.encounters = new EnumMap<>(Game.class);
        final Map<EncounterSlot, Encounter> redEncounters = new EnumMap<>(EncounterSlot.class);
        final Map<EncounterSlot, Encounter> blueEncounters = new EnumMap<>(EncounterSlot.class);
        if (encounters.length == 10) {
            // Both games have the same slots:
            for (int i = 0; i < encounters.length; i++) {
                redEncounters.put(EncounterSlot.values()[i], encounters[i]);
                blueEncounters.put(EncounterSlot.values()[i], encounters[i]);
            }
        } else {
            // Different encounter slots for each game; first 10 for blue, second 10 for red:
            for (int i = 0; i < 10; i++) {
                blueEncounters.put(EncounterSlot.values()[i], encounters[i]);
            }
            for (int i = 10; i < 20; i++) {
                redEncounters.put(EncounterSlot.values()[i - 10], encounters[i]);
            }
        }

        this.encounters.put(Game.BLUE, blueEncounters);
        this.encounters.put(Game.RED, redEncounters);
    }

    public Map<Game, Map<EncounterSlot, Encounter>> getEncounters() {
        return Collections.unmodifiableMap(encounters);
    }

    public boolean isBlinds() {
        return isBlinds;
    }
}
